<!-- This is a nested component for Graph Models  -->

<script lang="ts">
    import type {
        ModelMetadata,
        ModelFeatures,
    } from "$lib/stores/modelStore";
    import * as tf from "@tensorflow/tfjs";

    export let model: tf.GraphModel;
    export let metadata: ModelMetadata;
    export let features: ModelFeatures;

    // Helper to format tensor shapes
    function formatShape(shape: readonly (number | null)[] | undefined): string {
        if (!shape) return "N/A";
        return `[${shape.map((d) => (d === -1 ? "batch" : d)).join(", ")}]`;
    }
</script>

<div
    class="prose prose-sm max-w-none p-4 bg-slate-50 text-slate-800 rounded-lg"
>
    <h2 class="text-slate-900">Model Details</h2>

    <div class="grid grid-cols-2 gap-x-4">
        <div>
            <h4>Info</h4>
            <ul>
                <li><strong>Format:</strong> {metadata.format}</li>
                <li><strong>Generated By:</strong> {metadata.generatedBy}</li>
                {#if metadata.convertedBy}
                    <li><strong>Converted By:</strong> {metadata.convertedBy}</li>
                {/if}
            </ul>
        </div>
        <div>
            <h4>Architecture</h4>
            <ul>
                <li><strong>Inputs:</strong> {model.inputs.length}</li>
                <li><strong>Outputs:</strong> {model.outputs.length}</li>
            </ul>
        </div>
    </div>

    <h4>Signature</h4>
    <div>
        <h5>Inputs</h5>
        <ul class="list-none p-0">
            {#each Object.entries(metadata.signature.inputs) as [name, info] (name)}
                <li class="mb-2">
                    <strong class="font-mono">{name}</strong>
                    <ul class="!mt-1 !ml-4">
                        {#if info.dtype}<li>DType: {info.dtype}</li>{/if}
                        {#if info.shape}<li>Shape: {formatShape(info.shape)}</li>{/if}
                    </ul>
                </li>
            {/each}
        </ul>

        <h5>Outputs</h5>
        <ul class="list-none p-0">
            {#each Object.entries(metadata.signature.outputs) as [name, info] (name)}
                <li class="mb-2">
                    <strong class="font-mono">{name}</strong>
                    <ul class="!mt-1 !ml-4">
                        {#if info.dtype}<li>DType: {info.dtype}</li>{/if}
                        {#if info.shape}<li>Shape: {formatShape(info.shape)}</li>{/if}
                    </ul>
                </li>
            {/each}
        </ul>
    </div>

    {#if features?.features}
        <h4>Input Features ({features.features.length})</h4>
        <div class="flex flex-wrap gap-2">
            {#each features.features as feature (feature)}
                <span
                    class="bg-indigo-100 text-indigo-800 text-xs font-mono font-medium me-2 px-2.5 py-0.5 rounded-full"
                >
                    {feature}
                </span>
            {/each}
        </div>
    {/if}
</div>
